### PR TITLE
Compile under OS X and Clang

### PR DESCRIPTION
**Pull request by MegaByte**

### CODE REVIEW

**Comment by MrKrzYch00** [comment]
Is OS X also marked as __linux__? I can see you changing some checks for "is not defined WIN32" to "is defined linux", yet some are left unchanged.

Or maybe was it needed because some parts of the linux' code don't work on OS X? Is it thread affinitity? If so, does OS X have an alternative for that? - we should use that then or use OS X ways of threading as I did for windows BECAUSE pthread's affinity was not working with MSYS2's GCC on windows (required "SetThreadAffinityMask" which only works with windows' thread HANDLES). Last resort would be also to disable --aff (and also add proper information about it in commands list or/and when this command is used there), however I would rather have support for that, so it works on other OSes as well, in case end user needs to do so for performance, or other reasons.

**Comment by MegaByte** [comment]
OS X has pthreads, but not cpuset and related affinity functions and is not marked as Linux. Perhaps the checks could be changed to only exclude OS X (not sure if it works on BSD). OS X does have a different affinity API with less control: https://developer.apple.com/library/content/releasenotes/Performance/RN-AffinityAPI/

**Comment by MrKrzYch00** [comment]
Yes, this is what I did for windows. And as it didn't want to work with pthreads' created threads there I needed to convert all calls to use windows native ones. However, as I see OS X just requires different affinity function while pthreads can stay for it. No way for me to test that though as I don't have one.

So the only thing is for someone to add #ifdef for OS X and put a wrapping function there with anything else that is needed for it to work (structures?) OR to just make --aff not display in help menu/show information on those systems that it won't work.

Yea not quite sure if every system would support linux' thread affinity setting (or even pthreads itself). A configure file would be useful there to do all necessary checks...

Nonetheless I will test the compile process on all devices with your submitted code changes.

**Comment by MegaByte** [comment]
I added a layer to translate the affinity calls and reverted the Linux checks.

**Comment by MrKrzYch00** [comment]
Seems to be working OK on my systems with a small exception of using CC (which is linked to GCC anyway there) and adding -s to zopfli when compiling zopfling, but I don't see and negative effect of that.

**Pull request merged**
